### ISSUE TITLE
Plugins throw errors for buttons on the top or bottom of blocks when placed or interacted with.

### ISSUE THREAD

**Issue by Matmorcat** [NavidK0/Carbon#129]
When you place a button on the top or bottom of a block (added in 1.8), you get this error in Skript:
https://gist.github.com/Matmorcat/a423bcbc453c6a2a8e6b
When you click the buttom that is on the top or bottom of a block, you get this error with Skript and MyWarp:
https://gist.github.com/Matmorcat/6c9bf28dda421e3154cb

Using Carbon 1.7 and the latest Spigot 1.8 Protocol patch (20141001a).

**Comment by NavidK0** [comment]
I'm sorry to say that this can't be fixed currently because the plugin is using Bukkit, where as we're using spigot. The plugin doesn't know what to do with the top and bottom button placements. What I can recommend is that you simply don't use the new button placements with any Skript or external plugins until the 1.8 Spigot release, which will bring plugin compatibility.
