### ISSUE TITLE
Gson EnumTypeAdapter broken with Material enum when Carbon is loaded

### ISSUE THREAD

**Issue by Byteflux** [NavidK0/Carbon#134]
In order to understand how to serialize and deserialize enums, Gson uses EnumTypeAdapter, however, Gson will fail to initialize a type adapter for the Material enum if Carbon is loaded.

This happens with any Gson version that I've tested, whether the plugin is using the bundled version in CB or is shading in their own.

The relevant code in EnumTypeAdapter can be seen at: https://code.google.com/p/google-gson/source/browse/tags/gson-2.1/src/main/java/com/google/gson/internal/bind/TypeAdapters.java#686

The plugin I used in testing this was FactionsUUID, the source can be found at https://github.com/drtshock/Factions. It makes some use of the Material enum in its Gson-based configuration.

**Comment by Shevchik** [comment]
We are injecting new values int Enum $VALUES field, but we won't add fields to class because it is not possible. And i don't think that will be possible any time soon.
You will have to write your own type adapter like MassiveCore did.
https://github.com/MassiveCraft/MassiveCore/commit/ee2c51f60a95d4f37e8c561165083962e0b2e127
