### ISSUE TITLE
Problem on Startup

### ISSUE THREAD

**Issue by tylerpadgett** [NavidK0/Carbon#181]
I am trying to update to the latest build of Carbon and it shuts down as if I had stopped it.
I have the Latest Spigot Patch and the version before armor stands worked fine. 

Plugins: GroupManager, CommandSync, WorldEdit, PluginManag
er, NoLoginMessage, Launcher, TitleManager, Vault, UltimateParticles, FancyPorta
ls, ProtocolLib, Multiverse-Core, HolographicDisplays, WorldGuard, TeleportBow,
EnjinMinecraftPlugin, MCBans, MagicClock, Essentials, TouchscreenHolograms, Esse
ntialsSpawn, LibsDisguises, CompassNavigation, EssentialsChat, HubGadgets, WGCus
tomFlags, WGRegionEffects, Carbon

Here is the server log:

http://pastebin.com/dgPCXYCN

**Comment by Shevchik** [comment]
Learn to read.

**Comment by tylerpadgett** [comment]
@Shevchik I did if you would actually help people maybe they would get things done. Learn to not be a rude dumbass. I've read the plugin description and tried to do what it says... IT DID NOT WORK! Instead of saying "Learn to read." why dont you say "Did you try this, this, or this, etc." Maybe some people can't figure it out because some people are not as smart as you.

**Comment by NavidK0** [comment]
Excuse me? He's a rude dumbass? We've helped literally hundreds of people just like you who didn't read the damn plugin description. All you have to do is SCROLL down to installation prerequisites to find out that you need to turn late bind off and use the LATEST spigot patch! That's not hard at all, so is he still the dumbass for your inability to scroll down a page?

I'm sick of people asking the same god damn question over and over, and we always give the same answer: "LEARN TO READ!" because clearly they like wasting our time with PROBLEMS THAT ALREADY HAVE A SOLUTION!

I'm sorry, but it's extremely frustrating to get an e-mail every time someone doesn't read the main page, because I am not tech support for server admins, I am a developer who wants to fix new problems so that we can release a a stable build quickly. Every question that gets asked that's already been answered does nothing but wastes our time.

This entire statement was a waste of time as well, but I'm not even at home now, so whatever, can't work on Carbon now anyways.

**Comment by tylerpadgett** [comment]
@NavidK0  Ok then but I DID try what it said in the plugin description and I read it multiple times. It still did not work. I understand your frustration but you should still be nice about it because maybe some people can't actually figure it out.

**Comment by NavidK0** [comment]
When I say use the latest Spigot patch, I don't mean build #1649, I mean the patched version released on Oct. 1st.

Get it here: http://pancakeurl.com/spigot/

**Comment by tylerpadgett** [comment]
@NavidK0 Yes I know. It does not work.

**Comment by NavidK0** [comment]
Your error logs say you are using build #1649. Are you 100% sure you are loading the correct jar in your multicraft/mcmyadmin panel if you are using one?

The error itself means word for word that your spigot version is wrong and doesn't a function found in the latest patch.

**Comment by NavidK0** [comment]
*have

**Comment by tylerpadgett** [comment]
@NavidK0 
Yes I just downloaded that jar file with the link you sent me and it did the same thing.

**Comment by NavidK0** [comment]
Double check again that in spigot.yml that late bind is off. There is no other possibility for this error.

**Comment by NavidK0** [comment]
Also, paste your entire log file in pastebin, if you would.

**Comment by tylerpadgett** [comment]
It is @NavidK0

**Comment by tylerpadgett** [comment]
@NavidK0 It is hosted on my own computer if that helps. 
and ok.

**Comment by Shevchik** [comment]
Type /version, it should be git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10) for latest spigot patch.
Also don't forget to remove custom logger JVM flag if you have one.

**Comment by tylerpadgett** [comment]
@Shevchik Ok it actially does not say that which is weird because I downloaded it from @NavidK0 's link... so i'm trying again

**Comment by tylerpadgett** [comment]
Ok that fixed it.. The funny thing is that I originally had that and the first carbon worked but when I updated it, it stopped working. @Shevchik @NavidK0

**Comment by NavidK0** [comment]
Glad you fixed it in the end, sorry about earlier, I was just a bit angry.

**Comment by tylerpadgett** [comment]
@NavidK0 No I'm sorry I was the one that called him a rude dumbass and I understand.
