### ISSUE TITLE
Sponge removing water

### ISSUE THREAD

**Issue by TheMasterBlaster** [NavidK0/Carbon#81]
Sponge removes water even when its not next to it (One block away). Sponge should also remove water if water flows into Sponge block.
Edit: Im not sure if this is added to Carbon but, Sponge should not absorb more than 65 blocks of water (water closest to the sponge will be absorbed first).

**Comment by Jikoo** [comment]
I assume what you're referring to in the first part is that sponge isn't supposed to remove water if there is no water directly connecting the source to the sponge. That just involves more complex checks than what Carbon runs right now, doable but annoying.

The current system wouldn't be great for absorbing water that flows into a sponge - the event for water flow is pretty heavy, might be better to check when a block update is triggered for a sponge and do all water absorbing then. Seems like a certain amount of block physics handling will be needed anyway because of #68. Checking block physics would also give better plugin support (Worldediting in sponges won't cause drain now, etc.)

Carbon already only allows a sponge to absorb 65 blocks of water.

**Comment by TheMasterBlaster** [comment]
The issue with the current sponge setup is it removes all water around the sponge when it is triggered. It should only remove water it is touching. Water 4 or 5 blocks away not touching the sponge should not be removed.

**Comment by NavidK0** [comment]
Sponges fixed in Spigot 1.8, won't fix this.
